name: dartRuapu
version: 1.0.0
description: >-
  Use ruapu with Dart.

publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  path: ^1.9.0
  ffi: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0